### PR TITLE
checking duplicate routes

### PR DESCRIPTION
**Pull request by anon-hello**
checking duplicate routes.

Duplicate routes in routing map creates  a lot of confusion.
throwing exception before adding duplicate route looks better option.

Any comments are welcome....

### CODE REVIEW

**Comment by davidism** [comment]
You added a bunch of unrelated commits, please rebase this.  Do not create an anonymous class just to raise an execption, there's no way to catch it.  It's even worse because it doesn't even inherit from `Exception`.  Why do you think this should be an error in all cases?  This has failing tests, and doesn't provide any new tests demonstrating the change.

**Comment by devendra12** [comment]
Pardon please. I didn't notice it the unnecessary commits. Will rebase. :+1:

**Comment by devendra12** [comment]
the test case should not fail. After the test the map looks like this:

Map([<Rule '/foobar/' -> None>,
 <Rule '/users/' -> None>,
 <Rule '/foox' -> None>,
 <Rule '/foo/' -> None>,
 <Rule '/' -> None>,
 <Rule '/users/page/<page>' -> None>,
 <Rule '/foo/<testing>/edit' -> None>,
 <Rule '/foo/<testing>/' -> None>,
 <Rule '/<bar>/<blub>' -> None>,
 <Rule '/<blub>' -> None>,
 <Rule '/<blub>' -> None>])

Which contains "/<blub>" twice after one is resolved from -> "<int:blub>" to  "<blub>".

And that is what this PR is about.

**Comment by devendra12** [comment]
Are there any updates on this ? 
We are ERP system and use werkzeug. I was thinking to patch it in our framework but it would be better if is done in werkzeug.
Thanks.

**Comment by mitsuhiko** [comment]
I probably do not want to pull this in. This is hard to support for general cases. This seems like something that is easy to prevent from the application side anyways.

**Comment by devendra12** [comment]
So its like if I want to go to "/users" page, werkzeug lets you add any number of endpoints. User thinks everything is fine, but he is wrong. No Error or Even warning ??

**Comment by davidism** [comment]
Closing due to reasons stated, age, and lack of tests. If someone wants to work on this in the future, we need to test for and document any change in existing routing behavior.

**Pull request closed without merging**
