### PR TITLE
getattr(hashlib, 'algorithms', None) to

### PR DESCRIPTION
**Pull request by Lvl4Sword**
getattr(hashlib, 'algorithms_available', None)

### CODE REVIEW

**Comment by mitsuhiko** [comment]
The issue here is that `algorithms_available` and `algorithms` are doing different things. So I need to verify if changing one for the other actually works here.

**Comment by Lvl4Sword** [comment]
That's part of an issue I've bumped into, actually. It seems like Python 3.5 is interesting, as Blake isn't natively supported, but it's provided by my OpenSSL version. So, I'll poke at this a little more and see what I can do.

**Comment by mitsuhiko** [comment]
@Lvl4Sword I think the correct thing to do here would be to stop using our hack and instead use `hashlib.new` for string algorithm values.

**Comment by Lvl4Sword** [comment]
That's something I'm all for! Would be better than what's being used currently 😃

**Comment by mitsuhiko** [comment]
This code predates hashlib so a lot of what's there now does not really make sense any more in 2017. I'm happy to have this changed. Not sure if I can do it right now though.

**Comment by davidism** [comment]
@Lvl4Sword are you able to follow up and get this more in line with hashlib? We only support Python 2.7 and 3.4+ now, so that might make things easier.

**Comment by Lvl4Sword** [comment]
@davidism My initial approach was very poor, and it looks like there's more to be done than what I had.
There are a few things I'm working on currently, but it's something I'd like to help when I can.

**Comment by lepture** [comment]
Close it in favor of #1282

**Pull request closed without merging**
