### PR TITLE
Change how relative redirects are converted to absolute #693

### PR DESCRIPTION
**Pull request by boblehest**

### CODE REVIEW

**Comment by untitaker** [comment]
LGTM but please add tests.

**Comment by boblehest** [comment]
Sorry about that, I forgot to read your contribution guidelines.

**Comment by untitaker** [comment]
I'm no longer sure this is a good idea. @mitsuhiko?

**Comment by davidism** [comment]
Closing due to age and no description of what the issue was. Please open a new ticket to discuss if you still need this.

**Comment by davidism** [comment]
Oops, found the explanation in #693, but looks like your branch doesn't exist anymore so I can't reopen the PR. The last comment there says the latest RFC supports this, so I think this is reasonable. I'll cherry-pick this.

**Pull request closed without merging**
