### PR TITLE
log chained exceptions

### LINKED ISSUE #1350: Werkzeug does not properly log chained exceptions
When a chained exception is thrown, the Werkzeug server (used in development mode by Flask) logs only the "top" exception when it ought to log the whole chain.

To reproduce, run this Python script (with Flask installed):

```
from flask import Flask

app = Flask(__name__)


def do_something():
  raise ValueError("Foo")


@app.route('/exception_test', methods=['GET', 'POST'])
def process():
  try:
    do_something()
  except Exception as e:
    raise ValueError("Wrapper") from e

if __name__ == '__main__':
  app.config['PROPAGATE_EXCEPTIONS'] = True
  app.run(debug=False)
```

and then do `wget  http://127.0.0.1:5000/exception_test`. You should get something like:

```
 * Serving Flask app "chained_exception_mcve" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [30/Aug/2018 13:02:18] "GET /exception_test HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabbard/projects/gaia/gaia-alternatives/repos/vista-nlp-jvm/vista_nlp_serialization/chained_exception_mcve.py", line 20, in process
    raise ValueError("Wrapper") from e
ValueError: Wrapper
```

The desired output is:

```
 * Serving Flask app "chained_exception_mcve" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [30/Aug/2018 13:03:58] "GET /exception_test HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabbard/projects/gaia/gaia-alternatives/repos/vista-nlp-jvm/vista_nlp_serialization/chained_exception_mcve.py", line 20, in process
    raise ValueError("Wrapper") from e
Traceback (most recent call last):
  File "/Users/gabbard/projects/gaia/gaia-alternatives/repos/vista-nlp-jvm/vista_nlp_serialization/chained_exception_mcve.py", line 18, in process
    do_something()
  File "/Users/gabbard/projects/gaia/gaia-alternatives/repos/vista-nlp-jvm/vista_nlp_serialization/chained_exception_mcve.py", line 8, in do_something
    raise ValueError("Foo")
ValueError: Foo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabbard/projects/gaia/gaia-alternatives/repos/vista-nlp-jvm/vista_nlp_serialization/chained_exception_mcve.py", line 20, in process
    raise ValueError("Wrapper") from e
ValueError: Wrapper
```

The desired output can be achieved by editing the `Traceback` object from `tbtools.py` to
* save the `tb` object passed to its constructor
* changing https://github.com/pallets/werkzeug/blob/master/werkzeug/debug/tbtools.py#L280 to 
    ```
    buf = traceback.format_exception(self.exc_type, self.exc_value, self.tb,
                                 chain=True)
    ```

However, I am not sure whether or not this is a real solution because I don't know what consequences this might have elsewhere.

### Environment

* Python version: 3.6
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

[This issue was originally reported on Flask](https://github.com/pallets/flask/issues/2894#issuecomment-417396297) before it became apparent it was a Werkzeug issue.

### PR DESCRIPTION
**Pull request by eltonlaw**
fixes #1350

### CODE REVIEW

**Comment by eltonlaw** [comment]
example
Here's how it looks right now (using Flask)

**Comment by davidism** [comment]
There's still some issues here. It looks like we don't want to use `chain=True` in `exception`, since that sticks the whole thing at the top and bottom of the page, instead of just the exception. Instead, we want to to make `plaintext` understand the chained exceptions.

Started digging into this and basically we need to create groups of frames and let them handle the formatting. Python actually has a similar idea, but it's in [3.5+ only](https://docs.python.org/3/library/traceback.html#stacksummary-objects).

**Comment by davidism** [comment]
Rebased your original commmit, then made changes as described in the previous comment. Did a bunch of compat cleanup in `tbtools` too.

A lot of the processing moved from `Traceback` to the new `Group` object. Made the style for the chain info message look like the "Traceback (most recent call last)` header.

screen shot 2018-12-06 at 08 12 10
screen shot 2018-12-06 at 08 13 50

**Comment by davidism** [comment]
Turns out that `frame.f_lineno` is not accurate (at least in chained exceptions),  and `traceback.tb_lineno` should be used instead. I could not find an explanation for this difference.

**Pull request merged**
