### PR TITLE
Ability to use a callable timeout

### PR DESCRIPTION
**Pull request by msmol**
When caching, you can now pass a callable as the value for timeout

### CODE REVIEW

**Comment by davidism** [comment]
Is there a better example use case for this than a random timeout?

**Comment by RonnyPfannschmidt** [comment]
you can just use a callable proxy object there - werkzeug local proxies could already do that

```
from werkzeug.local import LocalProxy

@LocalProxy
def config_timeout():
  return 4 # the dice rolled it

print config_timeout
``

**Comment by msmol** [comment]
The problem with that approach, as far as I can tell I cannot do:

```python
from werkzeug.local import LocalProxy
from bar import baz

@LocalProxy
def config_timeout(foo)
    return baz.get('foo')

print(config_timeout) # how do I pass the LocalProxy the argument?
```

**Comment by RonnyPfannschmidt** [comment]
you dont - the test example you provided takes no arguments as well, so its not relevant to the problem at hand

**Comment by msmol** [comment]
Good point. I've updated my test to more accurately reflect the issue I am trying to solve with this. Thanks for the review.

**Comment by untitaker** [comment]
There is a lot of duplicated code across both cache subclasses and methods within those classes for normalizing a given timeout (falling back to the default timeout, checking if it's a callable). This duplication hasn't been introduced by this PR, but with it, it is worse.

If you don't mind I'll refactor this bit first so this PR only has to introduce new logic in one place.

**Comment by untitaker** [comment]
Take a look at https://github.com/pallets/werkzeug/pull/941

**Comment by untitaker** [comment]
Merged, please rebase :)

**Comment by RonnyPfannschmidt** [comment]
@msmol you could just pass in `LocalProxy(lambda: ...)` the problem wasn't changed

**Comment by untitaker** [comment]
Excellent, thanks!

**Comment by untitaker** [comment]
Actually I reverted this in master again... I've overlooked the usecase for this.

**Comment by untitaker** [comment]
So IOW I still don't understand how this is useful.

**Pull request merged**
