### PR TITLE
Add Accept-Ranges: bytes support for movie file seeking

### PR DESCRIPTION
**Pull request by Michael-S**
(Second attempt, first attempt failed continuous integration check due to extra blank lines.)
This modifies the werkzeug SharedDataMiddleware code so that a person serving movies (e.g. WebM/VP8) can click to the middle of the movie and have a HTTP range request to the server and get a 206 Partial Content result.

### CODE REVIEW

**Comment by yoyoprs** [comment]
It's not implemented on wsgi app side.

```
return environ.get('wsgi.file_wrapper', FileWrapper)(file, buffer_size, byterange)
TypeError: uwsgi_sendfile() takes at most 2 arguments (3 given)
```

**Comment by magne4000** [comment]
Actually this will fail if `Range` is malformed due to `int(byterangeval[6:-1])`.

**Comment by Michael-S** [comment]
I think this request can be closed, or someone else can take ownership if they wish.  For my project I switched to serving the static content with nginx and the dynamic content with werkzeug, and I only needed the partial content support in nginx - which already has it.

**Comment by magne4000** [comment]
We can actually close this. See #978

**Pull request closed without merging**
