### PR TITLE
Cookie value of more than 4096 bytes should not fail silently

### PR DESCRIPTION
**Pull request by Jaza**
For more details on cookie size limits, see:

http://stackoverflow.com/questions/640938/what-is-the-maximum-size-of-a-web-browsers-cookies-key

A similar ticket was opened for Django - see:

https://code.djangoproject.com/ticket/22242

The Django folks decided not to raise an exception when this happens, because they're using Python's standard Cookie library, so they'd have to duplicate the code to build / output the cookie value. Although they did update their documentation.

This is not an issue for Werkzeug, because it implements the raw encoding of the cookie by itself in `dump_cookie()`, rather than relying on Python Cookie. So, checking the size and raising an exception is a trivial change for Werkzeug.

### CODE REVIEW

**Comment by Jaza** [comment]
Is anyone able to review and/or merge this, please? There has been no activity in this PR for over a year, and nobody has reviewed it since I created it a year and a half ago.

**Comment by davidism** [comment]
I'm going through all the PRs right now, you may have noticed the uptick in notifications if you're watching the repo. This is on the list.

**Comment by untitaker** [comment]
LGTM, please add a changelog entry. Also we should probably add docs.

**Comment by untitaker** [comment]
Also we might consider adding a way to disable this restriction for very obscure usecases (custom clients?). After all this is not part an RFC afaict.

**Comment by untitaker** [comment]
(also @davidism feel free to request more reviews from me, I will get notified)

**Comment by davidism** [comment]
Maybe this should behave like `max_content_length`, where the property is set on the request (so can be overridden by a Flask config) and passed as an argument. Right now, you'd have to change a global variable, which doesn't seem like good practice.

We can still merge this version in, and then make another patch that extends it.

**Comment by untitaker** [comment]
Whichever route we choose, I'd be against releasing a version of Werkzeug that comes with this restriction without a good way to change/disable it.

**Comment by davidism** [comment]
It's possible to essentially disable it now, by setting the global to `sys.maxsize`. Not that that's particularly nice.

**Comment by ThiefMaster** [comment]
Monkeypatching is an awful way to do that :)

Maybe dump_cookie could take an argument with the default value being 4096. Since it's probably called from a method in the Response class it could be set to a class attribute - that way people could change the limit by subclassing Response (which is something that would work well in Flask too).

**Comment by davidism** [comment]
Merging this now, I have a patch for part 2 that I'll submit in a minute.

**Comment by davidism** [comment]
After some more discussion in #1109 I changed this to be a warning that describes how the size was being exceeded. It also moved the configuration into `Response`.

**Pull request merged**
