### PR TITLE
Handle setting invalid status on response consistently

### LINKED ISSUE #1658: Response allows invalid status
I was accidentally passing a string status like '200' from Flask.

```python
>>> from werkzeug import Response
>>> Response(status='200').status
'200'
```

This status isn't valid according to PEP 3333 and e.g. breaks Twisted's WSGI runner. Obviously the error was mine, but I thought perhaps Werkzeug should raise an error earlier.

Werkzeug already does some validation or coercion into the correct format:

```python
>>> Response(status='abc').status
'0 abc'
>>> Response(status='').status
Traceback (most recent call last):
  File "/Users/frazer/.pyenv/versions/venv/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 314, in _set_status
    self._status_code = int(self._status.split(None, 1)[0])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/frazer/.pyenv/versions/venv/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 202, in __init__
    self.status = status
  File "/Users/frazer/.pyenv/versions/venv/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 319, in _set_status
    raise ValueError("Empty status argument")
ValueError: Empty status argument
```

`status` only becomes invalid if both of these conditions are met:
1. `int(status)` doesn't raise
2. `len(status.split(None, 1)) == 1`

The current implementation:
https://github.com/pallets/werkzeug/blob/e7ba08f209477cb453f15113f9a4d527a6e81bfe/src/werkzeug/wrappers/base_response.py#L307-L320

If line 315 used the property setter instead (`self.status_code = `), the result would be valid:

```python
>>> Response(status='200').status
'200 OK'
```

### PR DESCRIPTION
**Pull request by raymond-devries**
Status setter now properly calls status code setter instead of setting status code directly.

fixes #1658

### CODE REVIEW

**Comment by raymond-devries** [comment]
Tests are failing on azure. Will investigate more as to why.

**Comment by ThiefMaster** [comment]
BTW, please don't put `Fixes #1658- ` and similar prefixes in the first line of commit  messages - they aren't really useful when looking at a compact git log, so they are better off in the later lines.

**Comment by raymond-devries** [comment]
Tests (Job Python 2.7 Windows), does not seem to be able to pass on Azure. It just keeps timing out. However, I can confirm it does pass all tests on python 2.7 on windows. I tested it manually on a windows computer.

**Comment by davidism** [comment]
Thanks for working on this at the PyCascades sprint! I refactored `_clean_status` so it's only one method, and rebased onto master. This will be in 2.0.

**Pull request merged**
