### PR TITLE
Fix whitespace %20 in uri_to_iri.

### PR DESCRIPTION
**Pull request by lepture**
Fix https://github.com/pallets/werkzeug/issues/1356

### CODE REVIEW

**Comment by davidism** [comment]
Should the unsafe characters in `iri_to_uri` be similarly updated?

**Comment by lepture** [comment]
No. I think `uri_to_iri` has no problem. But the `Request.url` has a problem, the `url` should be in `URI` instead of `IRI` according to the name.

**Comment by lepture** [comment]
Yeah. I think so too.

**Comment by davidism** [comment]
Closing this, working on a bigger change.

**Pull request closed without merging**
