### PR TITLE
Adding hypothesis. Using it on a few tests in the url module

### PR DESCRIPTION
**Pull request by alexk307**
I will add some more tests once I get the go ahead that this all looks good!

### CODE REVIEW

**Comment by untitaker** [comment]
Hypothesis does not work on Python 2.6. We need a way to skip those tests there.

**Comment by alexk307** [comment]
@untitaker good call, I'll see how I can do that.

**Comment by untitaker** [comment]
I suspect the easiest way is to separate hypothesis tests from other tests (in a separate folder), such that we never import them.

**Comment by alexk307** [comment]
OK cool

**Comment by alexk307** [comment]
@untitaker might not be what you had in mind but it works.

I couldn't figure out how to run tests by just importing a module. I tried to use `pytest.mark.skipif` but the `hypothesis.given`decorator is still evaluated regardless of the skip.

**Comment by alexk307** [comment]
Also fixes python >3.X builds. There was an unused import that I got merged `from sys import maxint`. But `maxint`is no longer in that package.

**Comment by untitaker** [comment]
I applied quite a few changes to master, so the huge if-statement is not needed anymore.

**Pull request merged**
