### PR TITLE
Mindless action in MultiPartParser constructor #963

### PR DESCRIPTION
**Pull request by alexpantyukhin**

### CODE REVIEW

**Comment by alexpantyukhin** [comment]
Hi @RonnyPfannschmidt I'm actually not sure what is wrong with python 2.6 there. I believe that the problem with such if statment. Maybe it would be ok to use not 'one line if'.

**Comment by RonnyPfannschmidt** [comment]
@alexpantyukhin no, the problem is flake8 droping python2.6 support

**Comment by alexpantyukhin** [comment]
oh. I see, thank you. It was strange for me why it failed after my commit.

**Comment by untitaker** [comment]
Fixed in #966, kicked over build.

**Comment by untitaker** [comment]
Huh?

**Comment by alexpantyukhin** [comment]
sorry)) just have some problems with git)) I created PR for the another issue in the different branch and it seems that accidentally dropped this commit.

**Comment by untitaker** [comment]
No problem, just create a new PR.

**Comment by alexpantyukhin** [comment]
I have create a new PR there https://github.com/pallets/werkzeug/pull/973

**Pull request closed without merging**
