### PR TITLE
Charset in Content-Type

### PR DESCRIPTION
**Pull request by gdoumenc**
Accept charset in content type

### CODE REVIEW

**Comment by gdoumenc** [comment]
If someone can perform full test as too complex for me, but very simple issue fixed

**Comment by wong2** [comment]
@gdoumenc what problem are you facing?

**Comment by gdoumenc** [comment]
Sorry for this so late answer (didn't see you reply.. apologize).
The issue was that in the test client (not in the app)  the charset was not defined in header. This produced an issue in oauth2 implementation test.
As it was log time ago I don't remember exactly.. But I can reinvestiguate if needed

**Comment by mitsuhiko** [comment]
The better fix for this is in f18b06a1d4b80c3e40cdbc8326baf49c23566237

**Pull request closed without merging**
