### PR TITLE
Ensure REQUEST_URI and RAW_URI stay in sync with path

### LINKED ISSUE #2151: test.Client.resolve_redirect keeps previous RAW_URI and REQUEST_URI
When `follow_redirects=True` is used, the second request will have an updated path, but the `environ` will not clear the synthesized `REQUEST_URI` and `RAW_URI` values from the previous request.

Example (using Flask):

    app = flask.Flask("test")

    @app.route("/e1")
    def endpoint():
        return flask.redirect("/e2")

    @app.route("/e2")
    def endpoint_destination():
        rv = {k: flask.request.environ[k] for k in ["PATH_INFO", "REQUEST_URI", "RAW_URI"]}
        return flask.jsonify(rv)

    client = app.test_client()
    rv = client.get("/e1", follow_redirects=True)
    assert rv.json == {
        "PATH_INFO": "/e2",
        "REQUEST_URI": "/e2",
        "RAW_URI": "/e2",
    }

Expectation:

    Expected :{'PATH_INFO': '/e2', 'RAW_URI': '/e2', 'REQUEST_URI': '/e2'}
    Actual   :{'PATH_INFO': '/e2', 'RAW_URI': '/e1', 'REQUEST_URI': '/e1'}

Environment:

- Python version: 3.6
- Werkzeug version: 2.0.1

---

I did only start to see this with 2.x. I think the fix might be as easy as doing the following in `resolve_redirect`:

```diff 
- builder = EnvironBuilder.from_environ(response.request.environ, query_string=qs)
+ builder = EnvironBuilder.from_environ(response.request.environ, path=path, query_string=qs)
```

### PR DESCRIPTION
**Pull request by mrcljx**
Attempt to fix #2151 - let me know if this warrants a regression test or a different approach.

### CODE REVIEW

**Comment by sirlantis** [comment]
The alternative probably is to [change the lines further below](https://github.com/sirlantis/werkzeug/blob/7e71e1d0046f04d45d8729957ecb4016b29e0a9d/src/werkzeug/test.py#L986-L993) where `builder.path` is set to also modify `request_uri`. Would be happy for some guidance there, then.

**Comment by davidism** [comment]
> if this warrants a regression test or a different approach.

Changes need tests. It's one of the checkboxes you removed from the PR template ;-)

**Comment by sirlantis** [comment]
> > if this warrants a regression test or a different approach.
> 
> 
> 
> Changes need tests. It's one of the checkboxes you removed from the PR template ;-)

Huh, I honestly haven't seen the template for some reason. Can't remember if I used a weird incantation to create the PR. Sorry about that.

**Comment by davidism** [comment]
Were you going to write a test for this?

**Comment by davidism** [comment]
This still needs a test.

**Pull request merged**
