### PR TITLE
Create a thread to reap death process

### LINKED ISSUE #810: zombie process created with multiple workers in run_simple
A simple server below with 2 processes creates zombie process on the server after serving a GET request. This is not observed with other server libraries (like `httpserver` with `Forkingmixin`).

~~~python
from werkzeug import serving

def application(environ, start_response):
        start_response('200 OK', [('Content-type', 'text/html')])
        return ['Hello World!!!']

serving.run_simple('127.0.0.1', 8080, application, processes=2)
~~~

Output of `ps aux | grep python` after a GET call:

~~~
user1    6824  0.1  0.0  82248 14528 pts/1    S+   09:28   0:00 python werkzeug_api.py
user1    6825  0.0  0.0      0     0 pts/1    Z+   09:28   0:00 [python] <defunct>
~~~

### PR DESCRIPTION
**Pull request by aplanas**
ForkingWSGIServer use `SocketServer.ForkingMixIn` to implement a
multiprocess server.  This class provides a workflow that collect
death process (process in Zombie status) before the
`process_request`.  This means that this process itself will be
in Zombie status at the end of the request, that will be eventually
collected during the next `process_request`.

To minimize transient Zombie process, `ForkingWSGIServer` is
creating a daemon thread (via `threading.Timer`) to call the
collector every (by default) 5 seconds.

Fixes #810

### CODE REVIEW

**Comment by mitsuhiko** [comment]
I want to understand if that is necessary. The entire server in werkzeug is really only supposed to be used for development anyways and short living.

**Comment by aplanas** [comment]
Not sure. Apparently OpenStack Ceilometer is using Werkzeug for the API in production.

**Comment by untitaker** [comment]
Any update on this?

**Comment by aplanas** [comment]
Not sure how I can help with making a decission. We added the patch in the openSUSE package, so avoid the creation of transient zombie process in Ceilometer. So far is working.

**Comment by RonnyPfannschmidt** [comment]
why does reaping that is using a time, also set up a new timer?

**Comment by aplanas** [comment]
@RonnyPfannschmidt oh good question: basically because is the solution that was more evident for me (and with less number of lines). The timer is used to create a thread that will check if there are zombies around. In the original code this check is done after a new request from the client.

The timer wake me up one time, so for the next time I need to create a new timer [1]

[1] https://docs.python.org/2/library/threading.html#timer-objects

**Comment by RonnyPfannschmidt** [comment]
my bad, i missremembered the api behaviour

**Comment by davidism** [comment]
Closing this because all it would do is clean up processes possibly faster than "the next request". I don't think it's a big deal that the dev server has a process left over for a little too long.

**Pull request closed without merging**
