### PR TITLE
Added logging if server name doesn't match.

### PR DESCRIPTION
**Pull request by Alexis-benoist**
Fix https://github.com/mitsuhiko/werkzeug/issues/760

### CODE REVIEW

**Comment by untitaker** [comment]
This will fire every request, which is probably not what we want?

**Comment by Alexis-benoist** [comment]
That's right! Do you think it would be a better idea to just issue this message at start time?

**Comment by untitaker** [comment]
I don't know if it's possible *on start*, but warning only on the first request seems doable.

**Comment by untitaker** [comment]
@Alexis-benoist Any update on this?

**Comment by jlark** [comment]
Is this a dead PR?

**Comment by untitaker** [comment]
I think so.

**Comment by Alexis-benoist** [comment]
I didn't had any time to see that.

**Comment by untitaker** [comment]
Closing due to inactivity.

**Pull request closed without merging**
