### PR TITLE
Exclude temporary files from reloader.

### LINKED ISSUE #1333: Reloader option to exclude watch paths
Seems like the server gets reloaded when `gen_py` caching files (created by the `win32com` module) are written or modified (in a temporary directory):

```
 * Detected change in 'C:\\Users\\X\\AppData\\Local\\Temp\\gen_py\\3.6\\C866CA3A-32F7-11D2-9602-00C04F8EE628x0x5x4\\__pycache__\\SpVoice.cpython-36.pyc', reloading
 * Detected change in 'C:\\Users\\X\\AppData\\Local\\Temp\\gen_py\\3.6\\C866CA3A-32F7-11D2-9602-00C04F8EE628x0x5x4\\__pycache__\\_ISpeechVoiceEvents.cpython-36.pyc', reloading
```
This seems to happen quite often. Any way for this to be prevented?

(Using Python `3.6`, Flask `1.0.2`, Werkzeug `0.14.1` on `Win10 64bit`. `FLASK_ENV=debug`, `FLASK_DEBUG=1`)

*Edit*: this also causes occasional cache corruptions (causing runtime errors and requiring wiping the `gen_py` directory to resolve) since it abruptly cuts out the process while it is writing (usually several files) to disk.

### PR DESCRIPTION
**Pull request by teymour-aldridge**
Fixes #1333.

### CODE REVIEW

**Comment by davidism** [comment]
This looks correct, but I wish I could confirm it. I don't use Windows or win32com.

**Comment by davidism** [comment]
I'm also worried that this will break the reloader if the virtualenv was created in the temp directory.

**Comment by teymour-aldridge** [comment]
That's true. I guess the best thing to do is to ask some people to try it?
I think that these issues are pretty specific to individual machines/setups (there's no general trend) so it might be best to have an environment variable which is a list of glob patterns for directories to exclude so that it can be optionally enabled if people start getting problems.

**Comment by davidism** [comment]
Yes, I think I might want to rework this to allow passing in a list of excluded paths, since it's already possible to pass a list of extra paths. I think there's a request for that somewhere.

**Comment by teymour-aldridge** [comment]
I'm happy to alter the PR to do that.

**Comment by davidism** [comment]
Could have sworn there were issues in Werkzeug or Flask about it, but couldn't find any. Let's create a new PR for passing a list to exclude.

**Comment by teymour-aldridge** [comment]
Ok – should I create an issue first?

**Comment by davidism** [comment]
It can still reference the one linked here, I'll add a comment about the solution I'm thinking of.

**Comment by teymour-aldridge** [comment]
Sounds good!

**Pull request closed without merging**
