### PR TITLE
Cache: improves threshold management in FScache

### PR DESCRIPTION
**Pull request by blixhavn**
* Adds cache element to maintain element count, to improve speed
  with very large caches.

* Supports disabling threshold by setting to zero.

### CODE REVIEW

**Comment by blixhavn** [comment]
@ThiefMaster Is the Travis CI failing anything other than a random failure? It seems unrelated to my work at least.

**Comment by davidism** [comment]
The cache tests randomly fail on Travis for some reason. Don't worry if those are the only failures. I'm re-running that job.

**Comment by blixhavn** [comment]
@davidism Any ETA on that release?

**Comment by davidism** [comment]
It was released a week ago.

**Comment by blixhavn** [comment]
Ah ok. Great :)

**Pull request merged**
