### PR TITLE
Added edge browser detection

### PR DESCRIPTION
**Pull request by doekman**
In response to issue https://github.com/pallets/werkzeug/issues/818

### CODE REVIEW

**Comment by fdenzer** [comment]
Documentation does not seem to match this commit:
neither [v0.14](http://werkzeug.pocoo.org/docs/0.14/utils/#module-werkzeug.useragents) nor development version of today (2018-02-06) do not include 'edge' as a possible user agent.

**Comment by doekman** [comment]
I forgot to update the docs. Luckily, someone [updated it last year](https://github.com/pallets/werkzeug/commit/524092d5743a44b6434302ccf625616bd7ac0fe3#diff-888dba64558ce3a6989d02891c996eeb) on master. You should have it.

**Comment by fdenzer** [comment]
Actually, for me 'chrome' at version 62 is detected for Edge of our current (corporate) Windows 10.

Did detection break? UserAgentParser does hold the 'edge' case, in my testcase it is just never used. 🤔

**Comment by doekman** [comment]
I have version `0.14.1` of werkzeug running and it detects edge just fine. The user-agent I got from edge: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134`.

@mitsuhiko  About the documentation: could it be the documentation build has problems? The documentation isn't date/time stamped, and I also don't see a commit hash of the last commit.

**Comment by fdenzer** [comment]
I guess I should open a new bug, since
`('Mozilla/5.0 (Windows NT 10.0; Win64; x64; WIA enabled) AppleWebKit/537.36 '
 '(KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763')`

gets detected as chrome 64, not edge 18.

**Comment by doekman** [comment]
@fdenzer I think we're missing something here. When I use your userAgent-string, it detects edge... If you [open this site](https://apawa.archipunt.nl/about), at the bottom it says what user agent it detects.

Are you sure you have the mentioned werkzeug-version?

    # If you use a virtual environment, don't forget to activate it.
    (venv) $ pip list
    Package            Version  
    ------------------ ---------
    ...
    Werkzeug           0.14.1

**Comment by fdenzer** [comment]
classical PEBKAC,

I was using the debian provided package, which as stated by
https://packages.debian.org/stretch/python3-werkzeug is 11.15 🙈

sorry for confusing my pep environments. issue withdrawn 😊

**Pull request merged**
