### PR TITLE
Enable unix domain socket binding

### PR DESCRIPTION
**Pull request by sergiosmcr**
If hostname starts with 'unix://', assume a
unix domain socket instead of a TCP socket.

I took the original solution from @runderwood PR #209 posted 4 years ago, and adjusted it to work in latest code.

### CODE REVIEW

**Comment by dajose** [comment]
@untitaker do you have some time to check this?

**Comment by sergiosmcr** [comment]
Can any one at Werkzeug check this?

**Comment by RonnyPfannschmidt** [comment]
at first glance the code looks good, i wont have time to test near term however

**Comment by untitaker** [comment]
LGTM too. I wonder if we can add a test for this, though test setup for the server is always very brittle...

**Comment by untitaker** [comment]
Also sorry for the super-slow response!

**Comment by sergiosmcr** [comment]
I'll write a test. I am not sure how to integrate it with your CLI though.

**Comment by untitaker** [comment]
I'm going to write a testcase, could you add appropriate docs? I.e. modify the docstring of run_simple and make_server and perhaps add an example in serving.rst

**Comment by sergiosmcr** [comment]
Sure. I will do soon

**Comment by untitaker** [comment]
Here's a shitty testcase, I'll refactor the entire server soon

**Comment by sergiosmcr** [comment]
Here is the requested documentation.
make_server docstring lacked of any parameter description, so I preferred not to modify it. Let me know if this change is enough.

**Comment by sergiosmcr** [comment]
Hey @untitaker It's been a while since I started this and I never fixed the test...
I've just rebased and have stronger wishes to merge this.
Would you help me to fix the test?

**Comment by untitaker** [comment]
Sorry I dont maintain this anymore.

On 27 December 2017 16:55:20 GMT+01:00, sergiosmcr <notifications@github.com> wrote:
>Hey @untitaker It's been a while since I started this and I never fixed
>the test...
>I've just rebased and have stronger wishes to merge this.
>Would you help me to fix the test?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/werkzeug/pull/1019#issuecomment-354133524

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sergiosmcr** [comment]
Oh ok.
Who can help me?

**Pull request merged**
