### PR TITLE
Allow exceptions to modify debugging tracebacks.

### PR DESCRIPTION
**Pull request by AnIrishDuck**
Extremely simple, checks for a "exc.werkzeug_debug_traceback" method and invokes that instead of the Traceback constructor when the corresponding exception is raised. This is useful for packages (like Mako) that autogenerate code and need to separately annotate tracebacks to translate source lines.

For an example of this project's usefulness, see this commit in the flask-mako extension: AnIrishDuck/flask-mako@ea6a05171caba6ec2e094467cb8087a148e391e3. This commit vastly improves the debugging environment when errors occur inside Mako templates.

### CODE REVIEW

**Comment by jab** [comment]
Just found my way here from benselme/flask-mako#2 and sorry to see this was just a testcase and changelog entry away from getting merged but it never happened.

@untitaker and other maintainers, if someone does that last bit of work, would you still merge this?

**Comment by RonnyPfannschmidt** [comment]
Jinja2 already fixes tracebacks, doesn't mako have the same something

**Comment by jab** [comment]
Thanks for taking a look @RonnyPfannschmidt. (Are you a werkzeug maintainer?) I'm new to this code (so @AnIrishDuck might have more to say) but from https://github.com/benselme/flask-mako/commit/0b537235fb125f427de7ab4acbbe5f6f6f2a258d it looks like the answer is yes, but flask-mako still needs this change to take advantage of it.
Would you still be willing to merge if someone adds the testcase @mitsuhiko requested?

**Comment by davidism** [comment]
Is this still needed? I'm not clear how the linked commit in Flask-Mako needs this. If someone adds a simple test case demonstrating what this does, it's fine to merge.

**Comment by AnIrishDuck** [comment]
> Is this still needed?

Yes, for the exception formatting in flask-mako to work. I'm not sure that flask-mako still works with new versions of werkzeug and mako, but that's not really your problem :)

> I'm not clear how the linked commit in Flask-Mako needs this.

It allows templating libraries (i.e. flask-mako) to modify the exception handling behavior in werkzeug. In particular, we need to be able to translate the stack differently. The comment by @RonnyPfannschmidt threw a bit of a wrench in the works - I was not aware that there was a way to modify error stacks directly in the templating library. That seems like a more appropriate long-term fix.

Unfortunately, I am no longer working on flask-mako (or indeed python) with enough frequency to pick this back up again. So the way forward is to close this, and wish whoever is audacious enough to do the necessary work on Mako good luck.

**Comment by jab** [comment]
> I'm not sure that flask-mako still works with new versions of werkzeug and mako

Running the latest versions of Flask (0.12.1), Werkzeug (0.12.1), Mako (1.0.6), and flask-mako (0.4) together is working fine for me.

(I'm using flask-mako because I'm using [Plim](http://plim.readthedocs.io/), which depends on Mako. Pretty big fan of Plim; surprised it (or something like it) doesn't seem to be more popular among Flask/Werkzeug users.)

**Comment by davidism** [comment]
@jab if you're interested, you can apply this PR as a patch from https://github.com/pallets/werkzeug/pull/206.patch, add a test, and submit a new PR.

**Comment by AnIrishDuck** [comment]
For the record, I still believe that this is the wrong solution for the problem. The right solution is to fix Mako to generate tracebacks like Jinja does.

It does suck that this solution works right now. The problem is that it's not guaranteed to stay that way. The matching changes in flask-mako introduce a lot of coupling between that extension and how werkzeug handles errors internally. werkzeug's error handling could presumably change in the future, which would be likely to break that code.

I also wouldn't be surprised if future Mako changes break that code.

It's much less likely said breakage will occur if Mako uses the same approach as Jinja. Moving the error handling logic closer to where the errors happen is just less brittle. But, ultimately my opinion isn't worth much because I can't help do the work.

**Comment by davidism** [comment]
Yeah, that makes sense. So let's leave this be then.

**Pull request closed without merging**
