### PR TITLE
LimitedStream inherits from io.IOBase.

### PR DESCRIPTION
**Pull request by mohamed-aziz**
Implementation for pallets/flask#2390

### CODE REVIEW

**Comment by davidism** [comment]
Do we need to override any methods of `IOBase` to pass through to the underlying stream or provide a sensible default?

**Comment by flexo** [comment]
The other methods of IOBase (listed [here](https://docs.python.org/3/library/io.html#class-hierarchy)) are pretty basic and seemed to have sensible enough defaults when I created a blank io.IOBase(); eg, writable() returns False, seekable() returns False.

**Comment by davidism** [comment]
Needs a test, preferably demonstrating that `json.loads` works on the stream now since that was the initial issue.

**Comment by davidism** [comment]
Changed to `io.RawIOBase` in #2620

**Pull request merged**
