### PR TITLE
Use iter_encoded in calculate_content_length

### LINKED ISSUE #705: Response.calculate_content_length doesn't use encoded self.response
The implementation of `calculate_content_length` doesn't encode the elements of `self.response` before using them:
https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/wrappers.py#L926

``` python
    def calculate_content_length(self):
        [...]
        return sum(len(x) for x in self.response)
```

In case self.response is composed of utf-8 encoded unicode strings, this will lead to an  invalid return length:

``` python
>>> from werkzeug import Response
>>> r = Response()
>>> r.response.append(u'你好')
>>> r.calculate_content_length()
2
>>> len(u'你好'.encode('utf-8'))
6
```

The easier solution to this would be to use `iter_encoded` inside `calculate_content_length`, but would decrease performances given the data would be encoded two time (for calculating content-lenght, then for actualy writing the data)

### PR DESCRIPTION
**Pull request by alexpantyukhin**
Fix #705

### CODE REVIEW

**Comment by untitaker** [comment]
Thanks, could you remove the issue URL from the title and put `fix #705` into the body?

**Comment by alexpantyukhin** [comment]
sure! Done.

**Comment by alexpantyukhin** [comment]
Actually I don't like the approach. It would be cool to encode response one time and use it for content_length and other places. But it needs much more changes which can bring other errors.

**Comment by untitaker** [comment]
I'd actually welcome a PR that refactors `get_data` such that it supports a cache like `Request.get_data`.

**Comment by alexpantyukhin** [comment]
@untitaker I have added a PR which implement caching for the Response's `get_data`  https://github.com/pallets/werkzeug/pull/992 . Also I have modified the current PR and `calculate_content_length`  now uses `get_data`

**Comment by alexpantyukhin** [comment]
Hi! what about this PR?

**Comment by untitaker** [comment]
It is dependent on #992 IMO and I still have to review that

**Comment by alexpantyukhin** [comment]
Not sure that these are dependent PR's.
The goal of the current PR is fixing the bug of incorrect calcualting of response. And the https://github.com/pallets/werkzeug/pull/992 PR is just caching. Actually which shouldn't affect on the interface of the `get_data`.

**Comment by untitaker** [comment]
Sorry for the late response. I think that `calculate_content_length` should never drain the data stream such that the user can't get the data anymore, which is why I think we need to land caching before we can do this PR

**Comment by untitaker** [comment]
Thanks, and sorry for the long wait.

**Pull request closed without merging**
