### PR TITLE
Werkzeug on Unix Domain Sockets

### PR DESCRIPTION
**Pull request by runderwood**
I patched Werkzeug's WSGI server to be capable of binding to Unix domain sockets.

### CODE REVIEW

**Comment by dajose** [comment]
can we reopen this? I'm in need for that feature @untitaker

**Comment by untitaker** [comment]
Please file a PR if you want this feature implemented in Werkzeug.

**Comment by dajose** [comment]
Thanks :) we'll look if @runderwood  solution is still working after these years and open a new PR

**Comment by davidism** [comment]
You can use the instructions here to pull this PR into your own clone: https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by sergiosmcr** [comment]
I am working with @dajose, @untitaker please check PR #1019

**Pull request closed without merging**
