### PR TITLE
Fixes broken "git fsck" due to corrupt commits

### PR DESCRIPTION
**Pull request by gn-jgeerds**
"git fsck" verifies the connectivity and validity of the objects in the
database. Unfortunately, this check fails because this repository contain 4x commits
which are not valid:

  missingSpaceBeforeEmail: invalid author/committer line - missing space before email

In order to run the check successfully, git provides a `fsck.skipList` configuration
option (<https://git-scm.com/docs/git-fsck#Documentation/git-fsck.txt-fsckskipList>). This
commit adds a single `.fsck-skiplist` file which contain these 4x commits.

From now on, you can configure `git config fsck.skipList .fsck-skiplist` and `git fsck`
will work again.

## Describe what you expected to happen.
`git fsck` should not return an error code on a clone of this repository.
## If possible, include a minimal, complete, and verifiable example to help us identify the issue.
```
❯ LANG=C git fsck
Checking object directories: 100% (256/256), done.
error in commit ab3c3bc6f72987f051960393d1f6c5d7bebc84b9: missingSpaceBeforeEmail: invalid author/committer line - missing space before email
error in commit 6ea37cd51e15c44c35770ebaa27ae252fef700d7: missingSpaceBeforeEmail: invalid author/committer line - missing space before email
error in commit 8f1cb158901c4f64fd5e934813fb670c31c0ec2f: missingSpaceBeforeEmail: invalid author/committer line - missing space before email
error in commit c4e0f1644b1700a3f5eb16fc5aac269af17854f0: missingSpaceBeforeEmail: invalid author/committer line - missing space before email
Checking objects: 100% (23418/23418), done.
```
## Describe what actually happened. Include the full traceback if there was an exception.
`git fsck` failed with exit code 4

```
❯ git show --pretty=raw ab3c3bc6f72987f051960393d1f6c5d7bebc84b9 | grep -E '(author|committer)'
author Thomas Waldmann<tw@waldmann-edv.de> <none@none> 1283431377 +0200
committer Thomas Waldmann<tw@waldmann-edv.de> <none@none> 1283431377 +0200
```

### CODE REVIEW

**Comment by ThiefMaster** [comment]
What about a name indicating it's git-related, like `.git-fsck-skiplist`?

**Comment by gn-jgeerds** [comment]
@ThiefMaster good point, fixed it.

**Comment by gn-jgeerds** [comment]
Fixed the outdated commit message with the second force push.

**Comment by davidism** [comment]
Where is this causing issues? The repo can still be cloned, pushed, etc. I acknowledge that there's a few bad emails, but I'm hesitant to add a file at the top level of the repository that must be manually used in an uncommon use case.

**Comment by davidism** [comment]
These commits happened in 2010. The docs for `git fsck` also show using `git config fsck.missingSpaceBeforeEmail warn` to warn instead of error on an issue that will no longer happen in modern Git. It doesn't seem like adding a file that will never be needed again is necessary.

**Pull request closed without merging**
