### PR TITLE
Fix _InteractiveConsole

### PR DESCRIPTION
**Pull request by mbertoldi**
With the last revision `locals` passed to `__init__` were lost. The original code was:

```python
def __init__(self, globals, locals):
        locals = dict(globals)
        locals.update(locals)
```

`locals` passed to `__init__` were lost at `locals = dict(globals)`.

### CODE REVIEW

**Comment by davidism** [comment]
Thanks. Can you rebase this onto 1.0.x and add a changelog?

```
git rebase --onto origin/1.0.x origin/master
```

**Comment by davidism** [comment]
Sorry, looks like you didn't run that rebase command correctly. You can use `git reflog` to find where to reset your repo, then try again.

**Comment by davidism** [comment]
It looks like you did the rebase, then merged master, but we can't merge master into the 1.0.x branch, so you'll need to back that out.

**Comment by mbertoldi** [comment]
I'm going to close this PR and open a new one, hopefully correct.
Is this the right way?

**Comment by davidism** [comment]
That's fine, sorry for the confusion! Be sure to branch off 1.0.x and target that branch when opening the PR.

**Comment by mbertoldi** [comment]
Closed and opened another (correct?) PR

**Comment by mbertoldi** [comment]
Closed

**Pull request closed without merging**
