### PR TITLE
Add option to exclude paths from reloader.

### LINKED ISSUE #1333: Reloader option to exclude watch paths
Seems like the server gets reloaded when `gen_py` caching files (created by the `win32com` module) are written or modified (in a temporary directory):

```
 * Detected change in 'C:\\Users\\X\\AppData\\Local\\Temp\\gen_py\\3.6\\C866CA3A-32F7-11D2-9602-00C04F8EE628x0x5x4\\__pycache__\\SpVoice.cpython-36.pyc', reloading
 * Detected change in 'C:\\Users\\X\\AppData\\Local\\Temp\\gen_py\\3.6\\C866CA3A-32F7-11D2-9602-00C04F8EE628x0x5x4\\__pycache__\\_ISpeechVoiceEvents.cpython-36.pyc', reloading
```
This seems to happen quite often. Any way for this to be prevented?

(Using Python `3.6`, Flask `1.0.2`, Werkzeug `0.14.1` on `Win10 64bit`. `FLASK_ENV=debug`, `FLASK_DEBUG=1`)

*Edit*: this also causes occasional cache corruptions (causing runtime errors and requiring wiping the `gen_py` directory to resolve) since it abruptly cuts out the process while it is writing (usually several files) to disk.

### PR DESCRIPTION
**Pull request by teymour-aldridge**
Add a `exclude_patterns` parameter to `run_simple`. This is a list of `fnmatch` patterns that are removed from the list of files to watch.

- fixes #1333

Checklist:

- [x] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [x] Add or update relevant docs, in the docs folder and in code.
- [x] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [x] Add `.. versionchanged::` entries in any relevant code docs.
- [x] Run `pre-commit` hooks and fix any issues.
- [x] Run `pytest` and `tox`, no tests failed.

### CODE REVIEW

**Comment by danihodovic** [comment]
@davidism @pgjones could we have a look at this PR? 

The reloader fails to detect changes if there is a file owned by root and permissions set to 0700 in the project directory. This is common if using docker-compose for development with locally stored database files.

**Comment by davidism** [comment]
@danihodovic please don't ping maintainers about their schedule. We will get to it when we have time.

**Comment by danihodovic** [comment]
It seems like you can pass ignore_patterns to watchdog. Maybe that's helpful

https://pythonhosted.org/watchdog/api.html#watchdog.events.PatternMatchingEventHandler.ignore_patterns

**Comment by davidism** [comment]
Had to do a rewrite due to #1945 rewriting the same code. Renamed it from `exclude_paths` to `exclude_patterns` to indicate it's using `fnmatch`. Use `fnmatch.filter` and sets to hopefully be a bit more efficient. `exclude_patterns` is taken into account when finding the paths to watch, and additionally in Watchdog to ignore events even if they were watched as part of a broader pattern.

**Pull request merged**
