### PR TITLE
Add 'None' as a legal value for samesite

### LINKED ISSUE #1549: SameSite value of 'None' not supported
Google's recent [blog post](https://blog.chromium.org/2019/05/improving-privacy-and-security-on-web.html
) describes changes on how they will enforce Cookies with SameSite value. The referenced [samesite cookies explained article](https://web.dev/samesite-cookies-explained/) and [RFC](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#section-4.1) both describe the ability to specify a SameSite value of 'None' the string (as opposed to None, not set) for SameSite.

The following today produces an error stating _invalid SameSite value; must be 'Strict', 'Lax' or None_
```python
resp.set_cookie('somekey', 'someval', domain='.mydomain.com', samesite='None')
```

You would think setting ```None``` would work but instead it unsets the key and prevents the samesite attribute from being present with a None (string) value in the headers.
```python
resp.set_cookie('somekey', 'someval', domain='.mydomain.com', samesite=None)
```

### PR DESCRIPTION
**Pull request by jsurls**
Fixes #1549

### CODE REVIEW

**Comment by davidism** [comment]
Thanks, would you mind adding a changelog entry for this?

**Comment by noelleleigh** [comment]
When can we expect to see this fix released? Chrome (and other browsers) are on a rapid timeline to require `SameSite=None; Secure` for third-party cookies: https://web.dev/samesite-cookies-explained/#changes-to-the-default-behavior-without-samesite

**Comment by davidism** [comment]
It is marked for the next release. I'm sorry, I can't speculate about the timeline of releases, they happen when I have enough time to make them happen.

**Comment by noelleleigh** [comment]
> It is marked for the next release. I'm sorry, I can't speculate about the timeline of releases, they happen when I have enough time to make them happen.

How does the release of a new Werkzeug version interact with a new release of Flask? Will there be a corresponding Flask release for these changes?

**Comment by davidism** [comment]
You'd upgrade Werkzeug, Flask depends on a minimum version which may get bumped later.

**Comment by VizualAbstract** [comment]
On February 4th, Shopify will require sessions abide by these same requirements. This update is important for that, or applications using it will fail. Really eager to see this released.

**Pull request merged**
