### PR TITLE
Always send bodies for 412 responses

### LINKED ISSUE #1231: Body of 412 responses not sent since ETag handling was added
On HTTP error, the response includes a message such as:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>413 Request Entity Too Large</title>
<h1>Request Entity Too Large</h1>
<p>The data value transmitted exceeds the capacity limit.</p>
```

Since Etag handling was added, 412 error response does not include this message anymore.

Below is the test script I used.

```python
#!/usr/bin/env python3

from werkzeug.exceptions import default_exceptions
from flask import Flask, abort


for http_exc in default_exceptions:

    app = Flask('test')
    client = app.test_client()

    @app.route('/')
    def test():
        abort(http_exc)

    response = client.get('/')
    assert response.status_code == http_exc

    if not response.get_data(as_text=True):
        raise ValueError('Missing data for HTTP error {}'.format(http_exc))
```

Feeding it to `git bisect` pointed me to https://github.com/pallets/werkzeug/commit/092e59a127de324517faa820e33b160372db8a85.

### PR DESCRIPTION
**Pull request by mitsuhiko**
This fixes #1231

### CODE REVIEW

**Comment by Allu2** [comment]
Any news on the progress of this PR? Recently released Flask 1.0 is depending on Werkzeug 0.14 which is suffering of this bug making using it iffy.
Is this pending some other PR to be merged?

**Comment by ikonst** [comment]
@mitsuhiko Do you plan to merge master and resolve the conflict?

**Comment by borgstrom** [comment]
We are also facing this issue when trying to upgrade to 0.14.

Is there an ETA for 0.15 to be released so we can pickup this fix?

**Comment by emedentsii** [comment]
Is there any news about version 0.15? I'm very interested in this fix too.

**Pull request merged**
